site_name: Wine Machine Learning
site_url: https://joewynn.github.io/mlops-for-fun/
repo_name: joewynn/mlops-for-fun

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
      icon: material/toggle-switch
      name: Switch to light mode
      primary: teal
      accent: lime
  icon:
    repo: fontawesome/brands/git-alt

plugins:
  - mkdocstrings

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/joewynn
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joseph-mwangoka/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/joewynn" target="_blank" rel="noopener">Joseph Wynn</a>