name: ci
on: 
  push: 
    branches: 
      - master
      - main
  pull_request: 
    branches: 
      - master
      - main
permissions: 
  contents: write
jobs: 
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3

      - name: Setup Python 3.7
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
      
      - name: Deploy
        run: |
          git pull
          mkdocs gh-deploy --force

      #- uses: actions/cache@v2
      #  with: 
      #    key: ${{ github.ref }}
      #    path: .cache
      #- run: mkdocs gh-deploy --force